_wandb:
    value:
        cli_version: 0.26.1
        e:
            08rr3zpsuvdqmicx44jd379hfca8mbzv:
                args:
                    - --batch-size
                    - "16"
                    - --window-sec
                    - "0.5"
                    - --iters
                    - "500"
                    - --initial-model
                    - xarm_model_1
                    - --wandb
                codePath: identify_pd.py
                codePathLocal: identify_pd.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "490577010688"
                        used: "243564425216"
                email: taeyun012@gmail.com
                executable: /home/capture15/anaconda3/envs/mujoco/bin/python
                git:
                    commit: 00317042ad69b1376abe47bb5e8808a9cbcfbf03
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-97da3786-a3c1-ce3b-77af-eb17cd36e038
                host: capture15-B760M-AORUS-ELITE
                memory:
                    total: "33409613824"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.35
                program: /home/capture15/sysid/identify_pd.py
                python: CPython 3.10.20
                root: /home/capture15/sysid
                startedAt: "2026-04-30T13:22:15.503619Z"
                writerId: 08rr3zpsuvdqmicx44jd379hfca8mbzv
        m: []
        python_version: 3.10.20
        t:
            "2":
                - 12
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 16
data_dir:
    value: /home/capture15/shared_data/capture/test_pd/cartesian/2/raw/arm
data_dt:
    value: 0.0073320865631103516
fitted_xml:
    value: /home/capture15/sysid/pd_id_results/xarm_model_1_pd_bs16_win0p5s-68step_iter500_lr3em02_seed0.mjcf
grad_clip_norm:
    value: 100
grad_mode:
    value: forward
initial_armature:
    value: 0.01
initial_mjcf:
    value: /home/capture15/sysid/pd_id/initial_mjcf/xarm_model_1.mjcf
iters:
    value: 500
lr:
    value: 0.03
model_dt_effective:
    value: 0.0018330216407775879
model_dt_original:
    value: 0.002
output:
    value: /home/capture15/sysid/pd_id_results/xarm_model_1_pd_bs16_win0p5s-68step_iter500_lr3em02_seed0.npz
positive_floor:
    value: 1e-08
seed:
    value: 0
sim_substeps:
    value: 4
w_pos:
    value: 100
w_tau:
    value: 1
w_vel:
    value: 10
window_sec:
    value: 0.5
window_steps:
    value: 68
